apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{CONTAINER_NAME}}-secret
  namespace: {{CONTAINER_NAMESPACE}}
stringData:
  # General
  PORT: "{{CONTAINER_PORT}}"
  HASH_PASSWORD_SALT: "{{HASH_PASSWORD_SALT}}"

  DATABASE_URL: "{{DATABASE_URL}}"