name: CI/CD

on:
  push: 
    branches: [main]

env:
  IMAGE_TAG: "${{vars.ARTIFACT_REGISTRY_ZONE}}-docker.pkg.dev/${{vars.GOOGLE_PROJECT_ID}}/${{vars.ARTIFACT_REGISTRY_REPOSITORY}}/laerthesouzadeveloper/translations-server:${{github.run_number}}"

jobs:
  CI:
    environment: dev
    runs-on: ubuntu-latest
    env:
      ARTIFACT_REGISTRY_ZONE: ${{vars.ARTIFACT_REGISTRY_ZONE}}
    steps:
      - uses: actions/checkout@v4.1.1

      - id: "google_auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}

      - name: Authenticate Docker with Artifact Registry
        run: cat ${{steps.google_auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://${{vars.ARTIFACT_REGISTRY_ZONE}}-docker.pkg.dev

      - name: Build docker image
        run: docker build -t "$IMAGE_TAG" . -f ./Dockerfile

  CD:
    environment: dev
    env:
      CONTAINER_NAME: ${{vars.CONTAINER_NAME}}
      CONTAINER_NAMESPACE: ${{vars.CONTAINER_NAMESPACE}}
      CONTAINER_HOST: ${{vars.CONTAINER_HOST}}
      CONTAINER_PORT: ${{vars.CONTAINER_PORT}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      HASH_PASSWORD_SALT: ${{secrets.HASH_PASSWORD_SALT}}
      IMAGE_PULL_SECRETS_NAME: ${{vars.IMAGE_PULL_SECRETS_NAME}}
      CONTAINER_REPLICAS: ${{vars.CONTAINER_REPLICAS}}
      HPA_MIN_REPLICAS: ${{vars.HPA_MIN_REPLICAS}}
      HPA_MAX_REPLICAS: ${{vars.HPA_MAX_REPLICAS}}
      IMAGE_TAG: laerthesouzadeveloper/translations-server:${{github.run_number}}
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2.1.0
        with:
          cluster_name: ${{vars.GKE_CLUSTER_NAME}}
          location: ${{vars.GKE_CLUSTER_ZONE}}

      - name: Replace k8s manifests variables
        run: |
          source ./deploy/scripts/env-replacer.sh ./deploy/k8s/secrets.yaml
          source ./deploy/scripts/env-replacer.sh ./deploy/k8s/deployment.yaml
          source ./deploy/scripts/env-replacer.sh ./deploy/k8s/hpa.yaml
          source ./deploy/scripts/env-replacer.sh ./deploy/k8s/service.yaml
          source ./deploy/scripts/env-replacer.sh ./deploy/k8s/ingress.yaml

      - name: Apply k8s manifests
        uses: Azure/k8s-deploy@v4.9
        with:
          namespace: ${{vars.CONTAINER_NAMESPACE}}
          manifests: ./deploy/k8s
      
