name: CI/CD

on:
  push: 
    branches: [main]

jobs:
  CI:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker hub authentication
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      - name: Build docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            laerthesouzadeveloper/translations-server:${{github.run_number}}
            laerthesouzadeveloper/translations-server:latest

  CD:
    environment: dev
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2.1.0
        with:
          cluster_name: ${{vars.GKE_CLUSTER_NAME}}
          location: ${{vars.GKE_CLUSTER_ZONE}}

      - name: Replace k8s manifests variables
        run: |
          ./deploy/scripts/env-replacer.sh ./deploy/k8s/secrets.yaml
          ./deploy/scripts/env-replacer.sh ./deploy/k8s/deployment.yaml
          ./deploy/scripts/env-replacer.sh ./deploy/k8s/service.yaml
          ./deploy/scripts/env-replacer.sh ./deploy/k8s/ingress.yaml

      - name: Apply k8s manifests
        uses: Azure/k8s-deploy@v4.9
        with:
          images: laerthesouzadeveloper/translations-server:${{github.run_number}}
          manifests: ./deploy/k8s
      
